spring:
  application:
    name: demo1
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 12345
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql